### ISSUE TITLE
JET precompilation error in Julia 1.11.5

### ISSUE THREAD

**Issue by matthijscox** [aviatesk/JET.jl#755]
I'm getting an error upon precompilation of JET:

```julia
julia> using JET
Precompiling JET...
Info Given JET was explicitly requested, output will be shown live
ERROR: LoadError: UndefVarError: `evaluate_call_recurse!` not defined in `JuliaInterpreter`
```

I'm on Julia 1.11.5 which restricts me to:
```
JET v0.9.20
JuliaInterpreter v0.9.46
```

Somehow these two package versions seem incompatible with each other, given that a function that JET 0.9.20 wants is missing in JuliaInterpreter 0.9.46.

I will try to upgrade to Julia 1.11.7 and see if that allows a higher version of JET. Or maybe I can use an older version of JET for a while?

**Comment by aviatesk** [comment]
Currently it's blocked on #751.

**Comment by matthijscox** [comment]
> Currently it's blocked on [#751](https://github.com/aviatesk/JET.jl/pull/751).

Thanks, so this means it should be fixed soon. 

I do suppose I could revert to some older set of versions that still works on 1.11, but I cannot yet find the right combination.

**Comment by matthijscox** [comment]
I added JET, Revise and JuliaInterpreter to my global environment in Julia 1.11.5 and suddenly it does compile?

```
Status `.julia\environments\v1.11\Project.toml`
⌅ [c3a54625] JET v0.9.20
⌅ [aa1ae85d] JuliaInterpreter v0.9.46
⌃ [295af30f] Revise v3.7.5
```

Not sure how that fixed it for me, but JET works now.
